version: "3.3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itransfer
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_HOST: db
        POSTGRES_USER: postgres
        POSTGRES_DB: itransfer
        SHARED_DIR: /data
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/mydata:/data
    links:
      - db
    environment:
      APP_PORT: 8080
      ENV: dev
      HOST: https://mydomain.com
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itransfer
      SHARED_DIR: /data
